#!/bin/bash
#
# Usage: downloadImages PATH...
# Downloads images of song specified by json file
# $@ - json files

# set -e

# Gets attribute from json file
# $1 - json file
# $2 - attribute
getAttribute() {
	cat "$1" | grep -o "$2"\":\"[^\"]* | sed 's/.*\"//'
}

# Downloads image from Google images
getImage () 
{ 
    wget -qO- "http://images.google.com/images?q=$(echo "$@" | sed 's/ /+/g')" -U "Firefox on Ubuntu Gutsy: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.14) Gecko/20080418 Ubuntu/7.10 (gutsy) Firefox/2.0.0.14" | grep -o '<img[^>]*>' | head -n1 | grep "src=\"[^\"]*" -o | sed 's/src=\"//' | wget -i- -O-
}

main() {
	for fileName in "$@"; do
		artist=$(getAttribute "$fileName" "artist")
		title=$(getAttribute "$fileName" "title")
		imageFilename=$(echo "$fileName" | sed 's/\.json/\.jpg/')
		if [[ "$artist" == "" ]]; then
			query=$(basename -s .json "$fileName" | sed 's/^[0-9 -]*//')
		else
			query="\"$artist\" \"$title\""
		fi
		echo "$query : $imageFilename"
		getImage "$query" > "$imageFilename"
	done
}

main "$@"
